apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fcp-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/fcp-api:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DATABASE_BACKEND
          value: firestore
        - name: STORAGE_BACKEND
          value: cloud
        - name: GCS_BUCKET
          value: fcp-uploads-146487230485
        - name: ENVIRONMENT
          value: production
        - name: FCP_DATA_DIR
          value: /tmp
        - name: LOG_LEVEL
          value: debug
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        - name: USDA_API_KEY
          valueFrom:
            secretKeyRef:
              name: usda-api-key
              key: latest
        - name: FDA_API_KEY
          valueFrom:
            secretKeyRef:
              name: fda-api-key
              key: latest
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-api-key
              key: latest
        - name: ASTRO_API_KEY
          valueFrom:
            secretKeyRef:
              name: astro-api-key
              key: latest
        - name: ASTRO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: astro-endpoint
              key: latest
        - name: FCP_TOKEN
          valueFrom:
            secretKeyRef:
              name: fcp-token
              key: latest
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
